// config/permissions.js

export const ROLES = {
  SYSADMIN: "sysadmin",
  ADMIN: "admin",
  COMPLIANCE_OFFICER: "complianceOfficer",
  MANAGER: "manager",
  AUDITOR: "auditor",
};

// Action-based permissions for each module
export const PERMISSIONS = {
  // User Management
  USER: {
    VIEW: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Group Management
  GROUP: {
    VIEW: [ROLES.SYSADMIN, ROLES.ADMIN],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Company Management
  COMPANY: {
    VIEW: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Site Management
  SITE: {
    VIEW: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Check Types
  CHECK_TYPE: {
    VIEW: [ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR, ROLES.COMPLIANCE_OFFICER],
    CREATE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    UPDATE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    DELETE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
  },

  // Rules
  RULE: {
    VIEW: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    CREATE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    UPDATE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    DELETE: [ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
  },

  // Questions
  QUESTION: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
    ],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
  },

  // Templates
  TEMPLATE: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
    ],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
  },

  // Programs
  PROGRAM: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Schedules
  SCHEDULE: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
    // Note: START permission handled by authorizeLeadAuditor middleware
  },

  // Audit Sessions
  AUDIT_SESSION: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Teams
  TEAM: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
  },

  // Observations
  OBSERVATION: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Problems
  PROBLEM: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Fix Actions
  FIX_ACTION: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
  },

  // Proofs
  PROOF: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AUDITOR],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
  },

  // Reports
  REPORT: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
    SUBMIT: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
  },

  // Approvals
  APPROVAL: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
    ],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.MANAGER],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN],
    APPROVE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER], // Admin only for override
    REJECT: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.COMPLIANCE_OFFICER], // Admin only for override
  },

  // Metrics
  METRIC: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
    ],
  },
};

// Helper function to get roles for specific module action
export const can = (module, action) => {
  return PERMISSIONS[module]?.[action] || [];
};
