// config/permissions.js

export const ROLES = {
  // ===== OLD ROLES (keep for backward compatibility) =====
  SYSADMIN: "sysadmin",
  ADMIN: "admin",
  COMPLIANCE_OFFICER: "complianceOfficer",
  MANAGER: "manager",

  // ===== NEW ROLES (for system refactor) =====
  AUDITOR: "auditor",
  SUPER_ADMIN: "superAdmin",
  GROUP_ADMIN: "groupAdmin",
  COMPANY_ADMIN: "companyAdmin",
  SITE_MANAGER: "siteManager",
  PROBLEM_OWNER: "problemOwner",
  APPROVER: "approver",
};

// Action-based permissions for each module
export const PERMISSIONS = {
  // User Management
  USER: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.AUDITOR,
      ROLES.SITE_MANAGER,
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.APPROVER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
  },

  // Group Management
  GROUP: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN, ROLES.COMPANY_ADMIN],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  },

  // Company Management
  COMPANY: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN],
    CREATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.GROUP_ADMIN, ROLES.SUPER_ADMIN],
    UPDATE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.GROUP_ADMIN, ROLES.SUPER_ADMIN],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.GROUP_ADMIN, ROLES.SUPER_ADMIN],
  },

  // Site Management
  SITE: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN, ROLES.COMPANY_ADMIN],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
  },

  // Check Types
  CHECK_TYPE: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN],
    CREATE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
    UPDATE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
    DELETE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
  },

  // Rules
  RULE: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN],
    CREATE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
    UPDATE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
    DELETE: [
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
    ],
  },

  // Questions
  QUESTION: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN, ROLES.AUDITOR, ROLES.APPROVER, ROLES.COMPANY_ADMIN],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
  
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
    ],
  },

  // Templates
  TEMPLATE: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN, ROLES.COMPANY_ADMIN],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
    ],
  },

  // Programs
  PROGRAM: {
    VIEW: [ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN, ROLES.COMPANY_ADMIN],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
  },

  // Schedules
  SCHEDULE: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.AUDITOR,
      ROLES.AUDITOR,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    // Note: START permission handled by authorizeLeadAuditor middleware
  },

  // Audit Sessions
  AUDIT_SESSION: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.AUDITOR,
      ROLES.APPROVER, // Approvers need to view sessions to close them
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
    ],
  },

  TEAM: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.AUDITOR,
      ROLES.SITE_MANAGER,
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.APPROVER, // Approvers need to see team members on audit session pages
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
  },

  // Observations
  OBSERVATION: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.AUDITOR,
      ROLES.SITE_MANAGER,
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.APPROVER,
      ROLES.COMPANY_ADMIN
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  },

  // Problems
  PROBLEM: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.AUDITOR,
      ROLES.APPROVER,
      ROLES.PROBLEM_OWNER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.AUDITOR, ROLES.SUPER_ADMIN],
  },

  // Fix Actions
  FIX_ACTION: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.APPROVER,
      ROLES.PROBLEM_OWNER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SITE_MANAGER,
      ROLES.PROBLEM_OWNER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SITE_MANAGER,
      ROLES.PROBLEM_OWNER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.PROBLEM_OWNER,
    ],
  },

  // Proofs
  PROOF: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.AUDITOR,
      ROLES.PROBLEM_OWNER,
      ROLES.APPROVER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
      ROLES.PROBLEM_OWNER,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.AUDITOR,
      ROLES.PROBLEM_OWNER,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.SITE_MANAGER,
      ROLES.AUDITOR,
      ROLES.PROBLEM_OWNER,
    ],
  },

  // Reports
  REPORT: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.APPROVER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.APPROVER,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.APPROVER,
    ],
    DELETE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.COMPANY_ADMIN,
      ROLES.APPROVER,
    ],
    SUBMIT: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
  },

  // Approvals
  APPROVAL: {
    VIEW: [
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.APPROVER,
      ROLES.AUDITOR,
      ROLES.COMPANY_ADMIN,
      ROLES.SITE_MANAGER,
    ],
    CREATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.APPROVER,
    ],
    UPDATE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.SUPER_ADMIN,
      ROLES.GROUP_ADMIN,
      ROLES.APPROVER,
    ],
    DELETE: [ROLES.SYSADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.GROUP_ADMIN],
    APPROVE: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.APPROVER,
    ], // Admin only for override
    REJECT: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      ROLES.APPROVER,
    ], // Admin only for override
  },

  // ... existing permissions
  // Metrics
  METRIC: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
    ],
  },

  // Question Assignments
  QUESTION_ASSIGNMENT: {
    VIEW: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.COMPLIANCE_OFFICER,
      ROLES.GROUP_ADMIN,
      ROLES.SUPER_ADMIN,
      
    ],
    ASSIGN: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
    UNASSIGN: [
      ROLES.SYSADMIN,
      ROLES.ADMIN,
      ROLES.MANAGER,
      ROLES.AUDITOR,
      ROLES.SUPER_ADMIN,
    ],
  },
};

// Helper function to get roles for specific module action
export const can = (module, action) => {
  return PERMISSIONS[module]?.[action] || [];
};
